export const PICTURE_FETCHING = 'PICTURE_FETCHING'
export const PICTURE_FETCH_SUCCESS = 'PICTURE_FETCH_SUCCESS'
export const PICTURE_FETCH_FAIL = 'PICTURE_FETCH_FAIL'
export const PICTURE_TAG_UPDATE = 'PICTURE_TAG_UPDATE'